import { useState, useEffect } from "react";
import { Plus, LogOut } from "lucide-react";
import { Header } from "./components/Header";
import { Footer } from "./components/Footer";
import { SubjectCard } from "./components/SubjectCard";
import { AddSubjectModal } from "./components/AddSubjectModal";
import { ProfileModal } from "./components/ProfileModal";
import { DataBackup } from "./components/DataBackup";
import { AttendanceCalendar } from "./components/AttendanceCalendar";
import { HolidayManager } from "./components/HolidayManager";
import { TodaySchedule } from "./components/TodaySchedule";
import { ShareProgress } from "./components/ShareProgress";
import { AlertBanner } from "./components/AlertBanner";
import { NotificationSettings } from "./components/NotificationSettings";
import { StreakBadge } from "./components/StreakBadge";
import { Button } from "./components/ui/Button";
import { storage, setUserId } from "./services/storage";
import { supabase } from "./lib/supabaseClient";
import { Auth } from "./components/Auth";

function App() {
  const [session, setSession] = useState(null);
  const [isSessionLoading, setIsSessionLoading] = useState(true);
  const [isResetMode, setIsResetMode] = useState(false);

  const [subjects, setSubjects] = useState([]);
  const [profile, setProfile] = useState(null);
  const [streak, setStreak] = useState({ current: 0, longest: 0 });
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isProfileModalOpen, setIsProfileModalOpen] = useState(false);
  const [isBackupModalOpen, setIsBackupModalOpen] = useState(false);
  const [isCalendarOpen, setIsCalendarOpen] = useState(false);
  const [isHolidaysOpen, setIsHolidaysOpen] = useState(false);
  const [isShareOpen, setIsShareOpen] = useState(false);
  const [isNotificationsOpen, setIsNotificationsOpen] = useState(false);
  const [loading, setLoading] = useState(true);

  const loadData = async () => {
    setLoading(true);
    const data = await storage.loadAllData();
    setSubjects(data.subjects);
    setProfile(data.profile);
    setStreak(data.streak);
    setLoading(false);
  };

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      handleSession(session);
    });

    const {
      data: { subscription },
    } = supabase.auth.onAuthStateChange((event, session) => {
      if (event === 'PASSWORD_RECOVERY') {
        setIsResetMode(true);
      }
      handleSession(session);
    });

    return () => subscription.unsubscribe();
  }, []);

  const handleSession = async (session) => {
    if (session) {
      const authId = session.user.id;
      setUserId(authId);

      // Check for local migration
      const localDeviceId = localStorage.getItem('attendance_device_id');
      if (localDeviceId && localDeviceId !== authId) {
        setIsSessionLoading(true); // show generic loader during migration
        await storage.migrateData(localDeviceId, authId);
        localStorage.removeItem('attendance_device_id');
      }

      setSession(session);
      loadData();
    } else {
      setSession(null);
    }
    setIsSessionLoading(false);
  };

  useEffect(() => {
    if (!loading && !profile) {
      // eslint-disable-next-line react-hooks/exhaustive-deps
      setIsProfileModalOpen(true);
    }
  }, [loading, profile]);

  const handleSaveProfile = async (name) => {
    const newProfile = await storage.setProfile(name);
    setProfile(newProfile);
  };

  const handleAddSubject = async (name, target) => {
    await storage.addSubject(name, target);
    // Reload subjects to get the ID generated by the DB
    const updatedSubjects = await storage.getSubjects();
    setSubjects(updatedSubjects);
  };

  const handleUpdateSubject = async (updatedSubject, isPresent = false) => {
    await storage.updateSubject(updatedSubject);
    const updatedSubjects = await storage.getSubjects();
    setSubjects(updatedSubjects);

    if (isPresent) {
      const result = await storage.recordActivity();
      setStreak(result.streak);
    }
  };

  const handleDeleteSubject = async (id) => {
    if (confirm("Are you sure you want to delete this subject?")) {
      await storage.deleteSubject(id);
      const updatedSubjects = await storage.getSubjects();
      setSubjects(updatedSubjects);
    }
  };

  const handleDataImported = () => {
    loadData();
  };

  const overallPercentage = subjects.length > 0
    ? Math.round(subjects.reduce((acc, sub) => acc + (sub.total === 0 ? 100 : (sub.attended / sub.total) * 100), 0) / subjects.length)
    : 0;

  if (isSessionLoading || (session && loading)) return <div className="min-h-screen bg-background flex flex-col items-center justify-center gap-4">
    <div className="w-8 h-8 flex items-center justify-center">
        <div className="w-8 h-8 rounded-full border-4 border-primary border-t-transparent animate-spin"></div>
    </div>
    <span className="text-muted-foreground font-medium">Loading Attendance...</span>
  </div>;

  if (!session || isResetMode) {
    return <Auth forceResetMode={isResetMode} onPasswordUpdated={() => setIsResetMode(false)} />;
  }

  const hour = new Date().getHours();
  const greeting = hour < 12 ? "Good morning" : hour < 18 ? "Good afternoon" : "Good evening";

  return (
    <div className="min-h-screen bg-background pb-20">
      <Header
        profile={profile}
        onEditProfile={() => setIsProfileModalOpen(true)}
        onOpenBackup={() => setIsBackupModalOpen(true)}
        onOpenCalendar={() => setIsCalendarOpen(true)}
        onOpenHolidays={() => setIsHolidaysOpen(true)}
        onOpenShare={() => setIsShareOpen(true)}
        onOpenNotifications={() => setIsNotificationsOpen(true)}
        onSignOut={() => supabase.auth.signOut()}
      />

      <main className="container mx-auto px-4 pt-8 max-w-5xl">
        {/* Alert Banners */}
        <AlertBanner subjects={subjects} streak={streak} />

        {/* Welcome Section */}
        <div className="flex flex-col md:flex-row justify-between items-end md:items-center mb-6 gap-4">
          <div>
            <h1 className="text-4xl font-bold mb-2">
              {profile ? `${greeting}, ${profile.name}!` : "My Attendance"}
            </h1>
            <p className="text-muted-foreground">Track your progress and stay safe.</p>
          </div>

          <div className="flex items-center gap-3">
            <StreakBadge streak={streak} />
            {subjects.length > 0 && (
              <div className="glass px-6 py-3 rounded-2xl flex items-center gap-4">
                <span className="text-sm font-medium text-muted-foreground">Overall</span>
                <span className="text-2xl font-bold text-primary">{overallPercentage}%</span>
              </div>
            )}
          </div>
        </div>

        {/* Today's Schedule */}
        <TodaySchedule />

        {/* Subjects Grid */}
        {subjects.length === 0 ? (
          <div className="text-center py-20 border border-dashed border-white/10 rounded-3xl bg-secondary/5">
            <p className="text-xl text-muted-foreground mb-6">No subjects added yet.</p>
            <Button onClick={() => setIsModalOpen(true)} size="lg" className="rounded-full shadow-lg shadow-primary/20">
              <Plus className="w-5 h-5 mr-2" />
              Add Your First Subject
            </Button>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {subjects.map(subject => (
              <SubjectCard
                key={subject.id}
                subject={subject}
                onUpdate={handleUpdateSubject}
                onDelete={handleDeleteSubject}
              />
            ))}

            <button
              onClick={() => setIsModalOpen(true)}
              className="flex flex-col items-center justify-center p-6 border-2 border-dashed border-white/10 rounded-2xl hover:border-primary/50 hover:bg-primary/5 transition-all group h-full min-h-[200px]"
            >
              <div className="w-12 h-12 rounded-full bg-secondary flex items-center justify-center mb-3 group-hover:scale-110 transition-transform">
                <Plus className="w-6 h-6 text-primary" />
              </div>
              <span className="font-medium text-muted-foreground group-hover:text-primary">Add New Subject</span>
            </button>
          </div>
        )}
      </main>

      {/* Modals */}
      <AddSubjectModal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        onAdd={handleAddSubject}
      />

      <ProfileModal
        isOpen={isProfileModalOpen}
        onClose={() => setIsProfileModalOpen(false)}
        onSave={handleSaveProfile}
        currentName={profile?.name}
      />

      <DataBackup
        isOpen={isBackupModalOpen}
        onClose={() => setIsBackupModalOpen(false)}
        onDataImported={handleDataImported}
      />

      <AttendanceCalendar
        isOpen={isCalendarOpen}
        onClose={() => setIsCalendarOpen(false)}
        subjects={subjects}
      />

      <HolidayManager
        isOpen={isHolidaysOpen}
        onClose={() => setIsHolidaysOpen(false)}
        onUpdate={loadData}
      />

      <ShareProgress
        isOpen={isShareOpen}
        onClose={() => setIsShareOpen(false)}
        profile={profile}
        subjects={subjects}
        streak={streak}
      />

      <NotificationSettings
        isOpen={isNotificationsOpen}
        onClose={() => setIsNotificationsOpen(false)}
      />

      <Footer />
    </div>
  );
}

export default App;
